### ISSUE TITLE
hi thanks your app! but i have a problem

### ISSUE THREAD

**Issue by mnkang89** [iZaL/insta-snap#3]
when i install your code and build in xcode or with react-native run-ios command, i constantly got an error about RCTVideo ... what is it? how can i solve this problem? plz help me!

by the way, thx your code!!

```


Ld build/Build/Products/Debug-iphonesimulator/Moshtaraiaty.app/Moshtaraiaty normal x86_64
    cd /Users/mnkang89/Desktop/insta-snap-master/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/Users/mnkang89/.rvm/gems/ruby-2.2.1/bin:/Users/mnkang89/.rvm/gems/ruby-2.2.1@global/bin:/Users/mnkang89/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/mnkang89/.rvm/bin:/Users/mnkang89/Library/Android/sdk/tools:/Users/mnkang89/Library/Android/sdk/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator -F/Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator -filelist /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Intermediates/Moshtaraiaty.build/Debug-iphonesimulator/Moshtaraiaty.build/Objects-normal/x86_64/Moshtaraiaty.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lc++ -fobjc-arc -fobjc-link-runtime -framework VideoToolbox /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTLinking.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTSettings.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTText.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -lRCTCamera -lRNVectorIcons -lRCTVideo -Xlinker -dependency_info -Xlinker /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Intermediates/Moshtaraiaty.build/Debug-iphonesimulator/Moshtaraiaty.build/Objects-normal/x86_64/Moshtaraiaty_dependency_info.dat -o /Users/mnkang89/Desktop/insta-snap-master/ios/build/Build/Products/Debug-iphonesimulator/Moshtaraiaty.app/Moshtaraiaty
ld: library not found for -lRCTVideo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
       	Ld build/Build/Products/Debug-iphonesimulator/Moshtaraiaty.app/Moshtaraiaty normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Moshtaraiaty.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/mnkang89/Desktop/insta-snap-master/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Moshtaraiaty.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (/Users/mnkang89/Desktop/insta-snap-master/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at /Users/mnkang89/Desktop/insta-snap-master/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/mnkang89/Desktop/insta-snap-master/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/mnkang89/Desktop/insta-snap-master/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/mnkang89/Desktop/insta-snap-master/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/mnkang89/Desktop/insta-snap-master/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/mnkang89/Desktop/insta-snap-master/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
gangminseongui-MacBook-Pro:instagangminseongui-MacBook-Pro:insgangmingangmingangmiganganggaggggggggaganggangminseongui-MacBook-Pro:instgangminseongui-MacBook-Pro:insta-snap-master mnkang89$

```

**Comment by UADACID** [comment]
i am still have an error for RCTVideo, can you help me?

**Comment by iZaL** [comment]
please delete the repo, and clone it again

**Comment by UADACID** [comment]
@iZaL thx, it work
